GET http://localhost:3001/tasks

###
POST http://localhost:3001/tasks/new
Content-Type: application/json

{
"text": "Make sex"
}

###

DELETE http://localhost:3001/tasks/delete/651fcd714a6205e7c156b7d0

###

PUT http://localhost:3001/tasks/update/651fe7510e7a3cd0103c46b3

